### ISSUE TITLE
Culler not working when there are too many users?

### ISSUE THREAD

**Issue by CarlosDominguezBecerril** [jupyterhub/jupyterhub-idle-culler#88]
### Bug description

Culler is not culling despite the last activity clearly being surpassed by the maximum time allowed. 

Current setup from our k8s logs:
```Starting service 'cull-idle': ['python3', '-m', 'jupyterhub_idle_culler', '--url=https://<url>:5081/hub/api', '--timeout=14400', '--cull-every=600', '--concurrency=10']```

We observe two things:
- user is using the default server
```
"last_activity": "2025-01-23T16:01:47.564284Z",
"started": "2025-01-13T09:57:08.123732Z",
```
- user is not using the analytics named server
```
"last_activity": "2025-01-20T12:06:54.100549Z",
"started": "2025-01-13T13:51:04.802281Z",
```

In the second case the last_activity was over 3days ago

Example obtained from `/api/users/<user>`

```json
{
    "server": "/user/<user>/",
    "created": "2023-02-06T09:37:18.564165Z",
    "admin": false,
    "name": "<user>",
    "kind": "user",
    "last_activity": "2025-01-23T16:06:51.635146Z",
    "roles": [
        "user"
    ],
    "auth_state": {
        "email": "<email>"
    },
    "pending": null,
    "groups": [
        "<groups>"
    ],
    "servers": {
        "": {
            "name": "",
            "full_name": "<user>/",
            "last_activity": "2025-01-23T16:01:47.564284Z",
            "started": "2025-01-13T09:57:08.123732Z",
            "pending": null,
            "ready": true,
            "stopped": false,
            "url": "/user/<user>/",
            "user_options": {
                "profile": "scipy-spark",
                "server_size": "model_training",
                "service_account": "data-science"
            },
            "progress_url": "/hub/api/users/<user>/server/progress",
            "full_url": null,
            "full_progress_url": null,
            "state": {
                "pod_name": "jupyter-<first_name>-2d<last_name>",
                "namespace": "jupyter-hub",
                "dns_name": "jupyter-<first_name>-2d<last_name>.jupyter-hub.svc.cluster.local"
            }
        },
        "analytics": {
            "name": "analytics",
            "full_name": "<user>/analytics",
            "last_activity": "2025-01-20T12:06:54.100549Z",
            "started": "2025-01-13T13:51:04.802281Z",
            "pending": null,
            "ready": true,
            "stopped": false,
            "url": "/user/<user>/analytics/",
            "user_options": {
                "profile": "python-3-analytics",
                "server_size": "default",
                "service_account": "data-science"
            },
            "progress_url": "/hub/api/users/<user>/servers/analytics/progress",
            "full_url": null,
            "full_progress_url": null,
            "state": {
                "pod_name": "jupyter-<first_name>-2d<last_name>--analytics",
                "namespace": "jupyter-hub",
                "dns_name": "jupyter-<first_name>-2d<last_name>--analytics.jupyter-hub.svc.cluster.local"
            }
        }
    }
}

```
### How to reproduce

I don't know how to reproduce this, we have jupyterhub deployed in several datacenters but only fails in our busiest one with **over 150 servers simultaneously** at the same time (not sure if it's an issue).

I'm afraid that the service is blocked / not running as expected because there are too many users

#### Expected behaviour

To cull the servers after they timeout

#### Actual behaviour

Is not culling the servers after the timeout

### Your personal set up

Latest version of jupyterhub and idle culler

### Logs

I can see the following logs from the culler:
⚠ Not sure if important but the fetching page 2 doesn't show the port just the url
```
Jan 23 16:41:12.885
nbt-hub
[I 250123 15:41:11 __init__:156] Fetching page 2 https://<url without port>/hub/api/users?state=ready&offset=50&limit=50

Jan 23 16:31:12.600
nbt-hub
File "/usr/local/lib/python3.10/dist-packages/jupyterhub_idle_culler/__init__.py", line 124, in fetch

Jan 23 16:31:12.600
nbt-hub
File "/usr/local/lib/python3.10/dist-packages/jupyterhub_idle_culler/__init__.py", line 142, in fetch_paginated

Jan 23 16:31:12.599
nbt-hub
File "/usr/local/lib/python3.10/dist-packages/jupyterhub_idle_culler/__init__.py", line 436, in cull_idle
```

Sometimes I also get

```
/usr/lib/python3.10/collections/__init__.py:431: RuntimeWarning: coroutine 'cull_idle.<locals>.handle_user' was never awaited
```

**Comment by CarlosDominguezBecerril** [comment]
After looking into the issue I found the problem:


During pagination the following line doesn't contain the port in the url which is causing an error
```
req.url = next_info["url"]
```
https://github.com/jupyterhub/jupyterhub-idle-culler/blob/main/jupyterhub_idle_culler/__init__.py#L158

I was able to fix if by
```
req.url = next_info["url"].replace(
    "<my_url>",
    "<my_url>:5081"
)
```

**Comment by CarlosDominguezBecerril** [comment]
We are using Z2JH. As for our configuration:

For our culler config:
```
# cull relates to the jupyterhub-idle-culler service, responsible for evicting
# inactive singleuser pods.
#
# The configuration below, except for enabled, corresponds to command-line flags
# for jupyterhub-idle-culler as documented here:
# https://github.com/jupyterhub/jupyterhub-idle-culler#as-a-standalone-script
#
cull:
  enabled: true
  users: false # --cull-users
  removeNamedServers: false # --remove-named-servers
  timeout: 14400 # --timeout (in seconds) -> server will shutdown if inactive after 4 hours
  every: 600 # --cull-every (in seconds) -> checks for expired servers every 10 minutes
  concurrency: 10 # --concurrency
  maxAge: 0 # --max-age
```


Installed versions that I believe matter:
```
"jupyterhub==5.2.0",
"jupyterhub-traefik-proxy==2.0.0",
"jupyterhub-idle-culler==1.4.0",
"jupyterhub-announcement",
"kubernetes==28.1.0",
```
